version: '3.7'
services:
    front:
      container_name: front
      build:
        context: ./sources/front
        dockerfile: Dockerfile
      volumes:
        - './sources/front:/front'
      ports:
        - '3000:3000'
      depends_on:
        - back
      environment:
        - NODE_ENV=development

    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"
        expose:
            - "27017"

    back:
        container_name: back
        build:
            context: ./sources/back
            dockerfile: Dockerfile
        volumes:
            - './sources/back:/back'
        ports:
            - '8080:8080'
        links:
            - mongo
        depends_on:
            - mongo
        environment:
            - NODE_ENV=development